import { v } from "convex/values";

export const enlistmentFields = {
  age: v.number(),
  isUsCitizen: v.boolean(),
  isSecondGeneration: v.boolean(),
  onRegistry: v.boolean(),
  isVeteran: v.boolean(),
  branch: v.string(),
  militaryRank: v.string(),
  militaryUnit: v.string(),
  militarySpecialty: v.string(),
  yearsOfService: v.string(),
  dischargeType: v.string(),
  combatDeployments: v.string(),
  hasPublicService: v.boolean(),
  publicServiceTypes: v.array(v.string()),
  policeAgencyType: v.string(),
  policeYears: v.string(),
  policeStatus: v.string(),
  policeTraining: v.string(),
  fireDepartmentType: v.string(),
  fireYears: v.string(),
  fireCertifications: v.string(),
  federalAgency: v.string(),
  federalYears: v.string(),
  federalClearance: v.string(),
  emsCertification: v.string(),
  emsYears: v.string(),
  correctionsAgency: v.string(),
  correctionsYears: v.string(),
  otherPublicService: v.string(),
  callsign: v.string(),
  email: v.string(),
  state: v.string(),
  specialty: v.string(),
  rank: v.string(),
  message: v.string(),
};

export const enlistmentInput = v.object(enlistmentFields);
